### ISSUE TITLE
viewCount + Likes?

### ISSUE THREAD

**Issue by haleyngonadi** [akoscz/YouTubePlaylist#3]
Hi. This is amazing! I'm wondering if there is a way to get viewCount and/or likes from YouTube?
Also, how do I remove the green bar to the right of the image?

**Comment by akoscz** [comment]
I updated the code so that the caching indicators are now only enabled for debug builds.  If you want to complete remove them even from debug builds then remove the following line from YouTubeFragment.onCreateView()
```Picasso.with(getActivity()).setIndicatorsEnabled(BuildConfig.DEBUG);```

As for viewCount and/or likes, that information is available through the 'videos' API
https://developers.google.com/youtube/v3/docs/videos
See the GetYouTubePlaylistAsyncTask.java for an example of how to invoke a YouTube v3 API.

**Comment by akoscz** [comment]
Check out the new updates to the code.  I added video duration, view count, likes count and dislikes count.  There's data available in the Video object for favorite count and comment count also, although I didn't add these numbers to the UI.  They are there if you need them though.

**Comment by haleyngonadi** [comment]
Thank you so much, You're the best.
