### ISSUE TITLE
Getting run-time error

### ISSUE THREAD

**Issue by behrouzbk** [akoscz/YouTubePlaylist#33]
I get the run-time error , please let me know how I can resolve it 

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: ca.genesissoft.tarlespeech, PID: 22458
                  java.lang.RuntimeException: Unable to start activity ComponentInfo(YoutubeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ProgressDialog.show()' on a null object reference
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
....
....
I/Process: Sending signal. PID: 22458 SIG: 9
Application terminated.

**Comment by akoscz** [comment]
Sounds like there is a race condition with updating the progress dialog as a new page of video's are being loaded.   I haven't been keeping the master branch up to date very much over the past couple of years.  Give the [dependecy-injection](https://github.com/akoscz/YouTubePlaylist/tree/dependecy-injection) branch a try since that branch has been getting some periodical updates.

**Comment by akoscz** [comment]
Should be fixed in the most recent version of master
