### ISSUE TITLE
Error while trying to access the API

### ISSUE THREAD

**Issue by tmorcinek** [akoscz/YouTubePlaylist#9]
I am getting this error from server when trying to access Youtube API. 

com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
"code": 403,
"errors": [
{
  "domain": "usageLimits",
  "message": "The Android package name and signing-certificate fingerprint, null and null, do not match the app restrictions configured on your API key. Please use the API Console to update your key restrictions.",
  "reason": "ipRefererBlocked",
  "extendedHelp": "https://console.developers.google.com/apis/credentials?project=796104768654"
}
],
"message": "The Android package name and signing-certificate fingerprint, null and null, do not match the app restrictions configured on your API key. Please use the API Console to update your key restrictions."
}

**Comment by akoscz** [comment]
While you're developing, you can get away with using a Browser Key.
https://developers.google.com/youtube/registering_an_application#Create_API_Keys
When you are ready to deploy your application, then create the Android Key since this step requires you to get the SHA1 of your signed APK.  Note that this SHA1 will change as you are developing your app, so it's a pain in the ass to constantly keep updating the Android key.

**Comment by tmorcinek** [comment]
Thanks very much for the answer!
